In [5]:
import numpy as np

In [28]:
x = [6, 4, 7, 2, 1]
w1 = [0, 4, -4, -5, 4]
b1 = 1
w2 = [2, 2, -4, 3, 0]
b2 = 1

v1 = [1, -2]
b3 = -1

v2 = [2, 3]
b4 = 0

v3 = [1,2]
b5 = 2

In [29]:
def relu(value):
    return max(0, value)

elementwise_relu = np.vectorize(relu)

def sigmoid(value):
    return 1 / (1 + np.exp(-value))

elementwise_sigmoid = np.vectorize(sigmoid)



In [30]:
w1_out = elementwise_relu(np.matmul(np.array(w1), np.array(x)) + b1)
w2_out = elementwise_relu(np.matmul(np.array(w2), np.array(x)) + b2)

layer1_out = np.array([w1_out, w2_out])
layer1_out

array([0, 0])

In [33]:
v1_out = elementwise_sigmoid(np.matmul(layer1_out, np.array(v1)) + b3)
v2_out = elementwise_sigmoid(np.matmul(layer1_out, np.array(v2)) + b4)
v3_out = elementwise_sigmoid(np.matmul(layer1_out, np.array(v3)) + b5)

layer2_out = np.array([v1_out, v2_out, v3_out])
layer2_out

array([0.26894142, 0.5       , 0.88079708])

In [34]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / np.sum(e_x)

final_out = softmax(layer2_out)
final_out

array([0.24367761, 0.30701748, 0.44930491])